language: java
jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r picturespot *
  - mkdir -p deploy
  - mv picturespot.zip deploy/picturespot.zip

deploy:
  - provider: s3
    access_key_id: AKIA4PAY5UU4VMHS4TMJ # Travis repo settings에 설정된 값
    secret_access_key: 0i9ohKefHJctq5+dO3qg2Wakj3ebMSVrDU3dPoSS # Travis repo settings에 설정된 값
    bucket: picturespot # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: AKIA4PAY5UU4VMHS4TMJ # Travis repo settings에 설정된 값
    secret_access_key: 0i9ohKefHJctq5+dO3qg2Wakj3ebMSVrDU3dPoSS # Travis repo settings에 설정된 값
    bucket: picturespot # S3 버킷
    key: picturespot.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: picturespot # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: picturespot-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

branches:
  only:
    - master
#Travis CI 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

#CI 실해 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - epfvkdlxj@naver.com