cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: epfvkdlxj@naver.com
    password: tjswn065311!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=구글아이디
#  spring.mail.password=구글비밀번호(배포시에는 2단계보안 앱비밀번호 사용해야함)
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true