cloud:
  aws:
    s3:
      bucket: picturespot
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIA4PAY5UU4VMHS4TMJ
      secretKey: 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

spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
#s3 관련 정보


