spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  freemarker:
    checkTemplateLocation: false
  profiles:
    include: oauth
  jpa:
    properties:
      hibernate:
        show_sql: true