cloud:
  aws:
    s3:
      bucket: market99bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIAVHWPNJXDNXDC2764
      secretKey: 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

spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
#s3 관련 정보


